package com.jobamax.appjobamax.enums


// contains cloud function name
enum class ParseCloudFunction(val value: String) {
    GET_TRACKING_STATUS("getTrackingStatus"),
    GET_JOB_SEARCH("getJobSearch"),
    GET_JOB_SEARCH_V2("getJobSearchV2"),
    GET_WISH_LIST_V2("getWishlistV2"),
    DROPOUT_ACTIONS("dropoutActions"),
    ADD_JOB_TO_WISHLIST("addJobToWishlist"),
    REMOVE_FROM_WISHLIST("removeFromWishlist"),
    GET_JOBS_LOGO("getJobsLogo"),
    DELETE_USER("deleteUser"),
    GET_JOB_TITLES("getJobTitles"),
    ADD_JOB_TITLE("addJobTitle"),
    IMPORT_FROM_LINKEDIN("importFromLinkedIn"),
    SAVE_SPENT_TIME("saveSpentTime"),
    SAVE_SWIPE_COUNT("saveSwipeCount"),
    APPLY_FOR_JOB("applyForJob"),
    MARK_AS_FAVORITE("markAsFavourite"),
    ARCHIVE_WISHLIST_JOB_ACTION("archiveWishlistJobAction"),
    UNARCHIVE_WISHLIST_JOB_ACTION("unArchiveWishlistJobAction"),
    GET_JOB_TITLE_FILTER_V1("getJobTitlesFilterV1"),
    GET_RECRUITMENT_SEEKERS_V2("getRecruitementSeekersV2"),
    GET_SOURCING_CRITERIA_V1("getSourcingCriteriaV1"),
    EDIT_SOURCING_CRITERIA_V1("editSourcingCriteriaV1"),
    SAVE_SOURCING_CRITERIA_V1("saveSourcingCriteriaV1"),
    GET_SOURCING_SEEKER_V1("getSourcingSeekersV1"),
    SOURCING_ACCEPT_V1("sourcingAcceptV1"),
    SOURCING_REJECT_V1("sourcingRejectV1"),
    HANDLE_ACTION_V1("handleActionV1"),
    TRIGGER_ZAP("triggerZap"),
    REMOVE_EMAIL_V1("removeEmailV1"),
    REPORT_ACTION("reportedAction"),
    HANDLE_FOLDER_ACTION_V1("handleFolderActionV1"),
    GET_FOLDERS_V1("getFoldersV1"),
    GET_FOLDER_SEEKERS_V2("getFolderSeekersV2"),
    IMPORT_CANDIDATE_V2("importCandidateV2"),
    GET_SELECTION_COUNT_V1("getSelectionCountV1"),
    HANDLE_MULTIPLE_ACTION_V1("handleMultipleActionV1"),
    RESET_PASSWORD_REQUEST("resetPasswordRequest"),
    SAVE_RATING_V1("saveRatingV1"),
    SEND_MSG_NOTIFICATION("sendMsgNotification"),
}